site_name: sqlorm
repo_url: https://github.com/hyperflask/sqlorm
repo_name: hyperflask/sqlorm
edit_uri: edit/main/docs/

nav:
  - index.md
  - engine.md
  - sessions-and-transactions.md
  - executing.md
  - sql-functions.md
  - models.md
  - sql-utilities.md
  - mapper.md
  - signals.md
  - schema.md
  - drivers.md
  - instrumentation.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.copy
    - toc.integrate
  icon:
    edit: material/pencil
  
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - callouts