name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Install the project
        run: uv sync --locked --all-extras --all-groups

      - name: Test with pytest
        run: uv run pytest tests --cov=sqlorm --cov-report=xml

      - name: Lint with Ruff
        run: uv run ruff check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
